<?php
// accounts/delete_journal_entry.php

require_once __DIR__ . '/../config.php';

if (!check_permission('Accounts', 'delete')) {
    die('Permission Denied.');
}

$entry_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;

if ($entry_id > 0) {
    $conn->begin_transaction();
    try {
        // First, check that this is a manual entry and not from a source document
        $stmt_check = $conn->prepare("SELECT source_document FROM scs_journal_entries WHERE id = ?");
        $stmt_check->bind_param("i", $entry_id);
        $stmt_check->execute();
        $entry = $stmt_check->get_result()->fetch_assoc();
        $stmt_check->close();

        if ($entry && $entry['source_document']) {
            throw new Exception("Cannot delete an entry automatically generated by another module.");
        }

        // Proceed with deletion
        $stmt_delete = $conn->prepare("DELETE FROM scs_journal_entries WHERE id = ?");
        $stmt_delete->bind_param("i", $entry_id);
        $stmt_delete->execute();
        
        if ($stmt_delete->affected_rows > 0) {
            log_activity('JOURNAL_DELETED', "Deleted journal entry with ID: " . $entry_id, $conn);
            $conn->commit();
            header("Location: journal_entries.php?success=deleted");
        } else {
            throw new Exception("Entry not found or already deleted.");
        }
        $stmt_delete->close();

    } catch (Exception $e) {
        $conn->rollback();
        header("Location: journal_entries.php?error=" . urlencode($e->getMessage()));
    }
} else {
    header("Location: journal_entries.php");
}
exit();
?>