<?php
// reports/sales_by_customer.php

require_once __DIR__ . '/../templates/header.php';

if (!check_permission('Reports', 'view')) {
    die('<div class="glass-card p-8 text-center">You do not have permission to access this page.</div>');
}

$page_title = "Sales by Customer Report - BizManager";

// --- FILTERING & DATA FETCHING ---
$customer_filter = isset($_GET['customer_id']) ? (int)$_GET['customer_id'] : 0;
$start_date = $_GET['start_date'] ?? '';
$end_date = $_GET['end_date'] ?? '';

$sql = "
    SELECT 
        c.id as customer_id,
        c.customer_name,
        c.email,
        COUNT(i.id) as total_invoices,
        COALESCE(SUM(i.total_amount), 0) as total_sales
    FROM scs_customers c
    LEFT JOIN scs_invoices i ON c.id = i.customer_id
    WHERE 1=1
";

$params = [];
$types = '';

if ($customer_filter > 0) {
    $sql .= " AND c.id = ?";
    $params[] = $customer_filter;
    $types .= 'i';
}
if (!empty($start_date)) {
    $sql .= " AND i.invoice_date >= ?";
    $params[] = $start_date;
    $types .= 's';
}
if (!empty($end_date)) {
    $sql .= " AND i.invoice_date <= ?";
    $params[] = $end_date;
    $types .= 's';
}

$sql .= " GROUP BY c.id ORDER BY total_sales DESC, c.customer_name ASC";

$stmt = $conn->prepare($sql);
if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$report_result = $stmt->get_result();

$customers_result = $conn->query("SELECT id, customer_name FROM scs_customers ORDER BY customer_name ASC");

?>

<title><?php echo htmlspecialchars($page_title); ?></title>

<div class="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
    <div>
        <h2 class="text-2xl font-semibold text-gray-800">Sales by Customer Report</h2>
        <p class="text-gray-600 mt-1">Analyze total revenue generated by each customer.</p>
    </div>
    <a href="sales_reports.php" class="mt-4 md:mt-0 inline-flex items-center px-4 py-2 bg-white/80 text-gray-700 rounded-lg shadow-sm hover:bg-white transition-colors">
        &larr; Back to Sales Reports
    </a>
</div>

<div class="glass-card p-4 mb-6">
    <form action="sales_by_customer.php" method="GET" class="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
        <div>
             <label for="customer_id" class="block text-sm font-medium text-gray-700">Customer</label>
             <select name="customer_id" id="customer_id" class="form-input mt-1 block w-full">
                <option value="0">All Customers</option>
                <?php while($customer = $customers_result->fetch_assoc()): ?>
                    <option value="<?php echo $customer['id']; ?>" <?php if($customer_filter == $customer['id']) echo 'selected'; ?>>
                        <?php echo htmlspecialchars($customer['customer_name']); ?>
                    </option>
                <?php endwhile; ?>
             </select>
        </div>
        <div>
             <label for="start_date" class="block text-sm font-medium text-gray-700">From</label>
             <input type="date" name="start_date" id="start_date" value="<?php echo htmlspecialchars($start_date); ?>" class="form-input mt-1 block w-full">
        </div>
        <div>
            <label for="end_date" class="block text-sm font-medium text-gray-700">To</label>
            <input type="date" name="end_date" id="end_date" value="<?php echo htmlspecialchars($end_date); ?>" class="form-input mt-1 block w-full">
        </div>
        <div>
            <button type="submit" class="w-full inline-flex justify-center py-2 px-4 rounded-md text-white bg-indigo-600 hover:bg-indigo-700">Filter</button>
        </div>
    </form>
</div>

<div class="glass-card p-6">
    <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-gray-700">
            <thead class="text-xs text-gray-800 uppercase bg-gray-50/50">
                <tr>
                    <th class="px-6 py-3">Customer</th>
                    <th class="px-6 py-3 text-center">Total Invoices</th>
                    <th class="px-6 py-3 text-right">Total Sales</th>
                    <th class="px-6 py-3 text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($report_result->num_rows > 0): ?>
                    <?php while($row = $report_result->fetch_assoc()): ?>
                    <tr class="bg-white/50 border-b border-gray-200/50">
                        <td class="px-6 py-4">
                            <div class="font-semibold text-gray-800"><?php echo htmlspecialchars($row['customer_name']); ?></div>
                            <div class="text-xs text-gray-500"><?php echo htmlspecialchars($row['email']); ?></div>
                        </td>
                        <td class="px-6 py-4 text-center font-bold text-lg"><?php echo $row['total_invoices']; ?></td>
                        <td class="px-6 py-4 text-right font-mono font-semibold text-green-700">
                            <?php echo htmlspecialchars($app_config['currency_symbol'] . number_format($row['total_sales'], 2)); ?>
                        </td>
                        <td class="px-6 py-4 text-center">
                            <a href="../crm/customer-details.php?id=<?php echo $row['customer_id']; ?>" class="font-medium text-indigo-600 hover:underline">
                                View Details
                            </a>
                        </td>
                    </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="4" class="px-6 py-4 text-center text-gray-500">No sales data found for the selected criteria.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>


<?php
require_once __DIR__ . '/../templates/footer.php';
?>